server:
  port: 9092
spring:
#  profiles:
#    active:
#      - test
#      - dev
#      - prod
  application:
    name: food-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fooddb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# configuration of discovery client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
