server:
  port: 9091
spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: user
    password: user
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: "Restaurant-Service"
    description: "This is a restaurant service where here your get restaurant information, Located in Config Server"
    version: "1.0V"
#configuration of eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
