spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: "{cipher}6532cadd8d795427470fdd9f52dec4d35eb6106066aa993efc600ff22152753a"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true

info:
  app:
    name: "User-Service Production"
    description: "This is a Production Environment of User service where you get a User information, Located in Cloud Config Server on GitHub"
    version: "1.0V"



